apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-05-18T19:21:41Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2861"
  uid: af1be73f-13a3-4ba7-897f-b150c3844816
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.60.239
  clusterIPs:
  - 10.103.60.239
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31145
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
